[tool.poetry]
name = "resumeio-to-pdf"
version = "0.1.0"
description = "Download your CV from resume.io as a PDF file"
authors = ["Felipe Allegretti <felipe@allegretti.me>"]
readme = "README.md"
license = "LICENSE.md"

[tool.poetry.dependencies]
python = "^3.9"
fpdf = "1.7.2"
requests = "2.28.1"

[tool.poetry.group.dev.dependencies]
black = "23.1.0"
isort = "5.12.0"

[tool.black]
line-length = 120
verbose = true
preview = true

[tool.isort]
profile = "black"